/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automatedcurrencyexchanger;

/**
 *
 * @author CouriousSoul
 */
import static CurrencyRecognition.RecognitionProcess.ImageResult;
import automatedcurrencyexchanger.ErrorLogs.PathConfiguration;
import automatedcurrencyexchanger.ImageProcess.ImageAcquisition;
import automatedcurrencyexchanger.ImageProcess.ImageProcessing;
import static automatedcurrencyexchanger.ImageProcess.ImageProcessing.SegmentSize;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.logging.Logger;
import javax.swing.JLabel;

public class CurrencyExchanger extends javax.swing.JFrame {
    private static final Logger APP_LOG = automatedcurrencyexchanger.ErrorLogs.ApplicationLogger.getNewLogger(ImageProcessing.class.getName());
    private static final PathConfiguration IMAGE_PATH = new PathConfiguration();
    private static final String MASTER_PATH = (IMAGE_PATH.GetImagePaths("original", null));
    private static final String SUB_PATH = (IMAGE_PATH.GetImagePaths("croped", null));
    private HashMap<Integer, Integer> addedDollors;
    boolean valuesAdded = false;
    public static JLabel mainImage;
    public static JLabel Logo;
    public static JLabel ParaOne;
    public static JLabel ParTwo;
    public static JLabel MergIm;
    public static JLabel GrayIm;

    /**
     * Creates new form CurrencyExchanger
     */
    public CurrencyExchanger() {
        initComponents();
        initiateHashMap();
        mainImage = this.jLabelMainImage;
        Logo= this.jLabelColorCheck;
        ParaOne =this.jLabelSegmentone;
        ParTwo=this.jLabelSegmenttwo;
        MergIm=this.jLabelMergedImage;
        GrayIm=this.jLabelGrayScalImage;

    }

    public void initiateHashMap() {
        addedDollors = new HashMap<>();
        addedDollors.put(5, 0);
        addedDollors.put(10, 0);
        addedDollors.put(20, 0);
        addedDollors.put(50, 0);
        addedDollors.put(100, 0);
    }

    public void addToList(int dollorVal) {
        int currentNumber = addedDollors.get(dollorVal);
        currentNumber++;
        addedDollors.replace(dollorVal, currentNumber);
        printDollorMetrix();
    }

    public  void printDollorMetrix() {
        String message = "";

        for (int key : addedDollors.keySet()) {
            if (addedDollors.get(key) > 0) {
                String tempMsg = "";
                tempMsg = "[" + key + " : " + addedDollors.get(key) + "]\n";
                message += tempMsg;
            }
        }
         jLabelDollarVallue.setText(message);
    }

    public static void getDValue(int Denominator) {
       
       // addToList(Denominator);
        
        
        System.out.println("GOT THE DOLLAR"+Denominator);
       
       
        
    }

 
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        AddDollars = new javax.swing.JButton();
        ButtonExchnage = new javax.swing.JButton();
        jLabelMainImage = new javax.swing.JLabel();
        jLabelDollarVallue = new javax.swing.JLabel();
        jLabelSegmentone = new javax.swing.JLabel();
        jLabelSegmenttwo = new javax.swing.JLabel();
        jLabelColorCheck = new javax.swing.JLabel();
        jLabelMergedImage = new javax.swing.JLabel();
        jLabelGrayScalImage = new javax.swing.JLabel();
        jLabelback = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("AUTOMATED CURRENCY EXCHANGE SYSTEM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 1330, 70);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("Press Continue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        AddDollars.setText("Exchange More");
        AddDollars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDollarsActionPerformed(evt);
            }
        });

        ButtonExchnage.setText("Exchange");
        ButtonExchnage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExchnageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddDollars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonExchnage, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(510, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddDollars)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonExchnage)
                .addGap(60, 60, 60))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(1140, 90, 210, 660);

        jLabelMainImage.setMaximumSize(new java.awt.Dimension(517, 218));
        jLabelMainImage.setMinimumSize(new java.awt.Dimension(517, 218));
        jLabelMainImage.setPreferredSize(new java.awt.Dimension(517, 218));
        getContentPane().add(jLabelMainImage);
        jLabelMainImage.setBounds(50, 100, 517, 218);

        jLabelDollarVallue.setText("Acqured Image");
        getContentPane().add(jLabelDollarVallue);
        jLabelDollarVallue.setBounds(50, 330, 540, 14);

        jLabelSegmentone.setMaximumSize(new java.awt.Dimension(225, 146));
        jLabelSegmentone.setMinimumSize(new java.awt.Dimension(225, 146));
        jLabelSegmentone.setName(""); // NOI18N
        jLabelSegmentone.setPreferredSize(new java.awt.Dimension(225, 146));
        getContentPane().add(jLabelSegmentone);
        jLabelSegmentone.setBounds(50, 370, 225, 146);

        jLabelSegmenttwo.setMaximumSize(new java.awt.Dimension(225, 146));
        jLabelSegmenttwo.setMinimumSize(new java.awt.Dimension(225, 146));
        jLabelSegmenttwo.setPreferredSize(new java.awt.Dimension(225, 146));
        getContentPane().add(jLabelSegmenttwo);
        jLabelSegmenttwo.setBounds(290, 370, 225, 146);

        jLabelColorCheck.setMaximumSize(new java.awt.Dimension(173, 146));
        jLabelColorCheck.setMinimumSize(new java.awt.Dimension(173, 146));
        jLabelColorCheck.setPreferredSize(new java.awt.Dimension(173, 146));
        getContentPane().add(jLabelColorCheck);
        jLabelColorCheck.setBounds(200, 530, 173, 146);

        jLabelMergedImage.setMaximumSize(new java.awt.Dimension(173, 146));
        jLabelMergedImage.setMinimumSize(new java.awt.Dimension(173, 146));
        jLabelMergedImage.setPreferredSize(new java.awt.Dimension(173, 146));
        getContentPane().add(jLabelMergedImage);
        jLabelMergedImage.setBounds(630, 160, 173, 146);

        jLabelGrayScalImage.setMaximumSize(new java.awt.Dimension(173, 146));
        jLabelGrayScalImage.setMinimumSize(new java.awt.Dimension(173, 146));
        jLabelGrayScalImage.setPreferredSize(new java.awt.Dimension(173, 146));
        getContentPane().add(jLabelGrayScalImage);
        jLabelGrayScalImage.setBounds(910, 160, 173, 146);

        jLabelback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SysImages/Back.jpg"))); // NOI18N
        getContentPane().add(jLabelback);
        jLabelback.setBounds(0, 0, 1370, 770);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        PathConfiguration ImPath = new PathConfiguration();
//
//        String masterPath = (ImPath.GetImagePaths("original", null));
//        ImageAcquisition.captureImage(masterPath);

        SegmentSize(1);
           Thread thread = new Thread() {
         
        @Override
        public void run() {
            
             getImages();
        }
    };
    thread.start();

    }//GEN-LAST:event_jButton1ActionPerformed
      
    
    public static void getImages() {
        File f = new File(MASTER_PATH);
if(f.exists() && !f.isDirectory()) { 
    

        
        ImageIcon MImg = new ImageIcon(MASTER_PATH);
        Image Mimage = MImg.getImage();
        Image newMImg = Mimage.getScaledInstance(517, 218,  java.awt.Image.SCALE_SMOOTH);
        MImg = new ImageIcon(newMImg);
        mainImage.setIcon(MImg);
                       
        ImageIcon LImg = new ImageIcon(SUB_PATH + "GreenSeal.jpg");
        Image Limage = LImg.getImage();
        Image newLImg = Limage.getScaledInstance(173, 146,  java.awt.Image.SCALE_SMOOTH);
        LImg = new ImageIcon(newLImg);
        Logo.setIcon(LImg);
        
        
        ImageIcon POImg = new ImageIcon(SUB_PATH + "image0.jpg");
        Image POimage = POImg.getImage();
        Image newPOImg = POimage.getScaledInstance(225, 146,  java.awt.Image.SCALE_SMOOTH);
        POImg = new ImageIcon(newPOImg);
        ParaOne.setIcon(POImg);
        
        ImageIcon PTImg = new ImageIcon(SUB_PATH + "image1.jpg");
        Image PTimage = PTImg.getImage();
        Image newPTImg = PTimage.getScaledInstance(225, 146,  java.awt.Image.SCALE_SMOOTH);
        PTImg = new ImageIcon(newPTImg);
        ParTwo.setIcon(PTImg);
        
        
        ImageIcon MRImg = new ImageIcon(SUB_PATH + "MergedImg.jpg");
        Image MRimage = MRImg.getImage();
        Image newMRImg = MRimage.getScaledInstance(173, 146,  java.awt.Image.SCALE_SMOOTH);
        MRImg = new ImageIcon(newMRImg);    
        MergIm.setIcon(MRImg);
        
        
        ImageIcon GImg = new ImageIcon(SUB_PATH + "GrayScal.jpg");
        Image Gimage = GImg.getImage();
        Image newGImg =Gimage.getScaledInstance(173, 146,  java.awt.Image.SCALE_SMOOTH);
        GImg = new ImageIcon(newGImg);    
        GrayIm.setIcon(GImg);
}


    }
    private void AddDollarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDollarsActionPerformed
        
         // TODO add your handling code here:
    }//GEN-LAST:event_AddDollarsActionPerformed

    private void ButtonExchnageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExchnageActionPerformed
        String message = "";
        int total = 0;

        for (int key : addedDollors.keySet()) {
            int number = addedDollors.get(key);

            if (number > 0) {
                String tempMessage = "You have " + number + "of $" + key + " notes \n";
                total += (key * number);
                message += tempMessage;
            }
        }

        message += "\n\n";
        message += "Total is" + total;
        // jLabel1.setText(message);        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonExchnageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrencyExchanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrencyExchanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrencyExchanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrencyExchanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrencyExchanger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDollars;
    private javax.swing.JButton ButtonExchnage;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelColorCheck;
    private javax.swing.JLabel jLabelDollarVallue;
    private javax.swing.JLabel jLabelGrayScalImage;
    private javax.swing.JLabel jLabelMainImage;
    private javax.swing.JLabel jLabelMergedImage;
    private javax.swing.JLabel jLabelSegmentone;
    private javax.swing.JLabel jLabelSegmenttwo;
    private javax.swing.JLabel jLabelback;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
