/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automatedcurrencyexchanger;
import static CurrencyRecognition.RecognitionProcess.ImageResult;
import NuralNet.PatternNeuralNet;
import static automatedcurrencyexchanger.ImageProcess.ImageProcessing.SegmentSize;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author CouriousSoul
 */
public class InitiateSystem extends javax.swing.JFrame {
   

    /**
     * Creates new form InitiateSystem
     */
    public InitiateSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabelNnTrained = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jButton1.setText("Start System");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelNnTrained.setText("jLabel1");

        jLabel.setBackground(new java.awt.Color(255, 255, 255));
        jLabel.setForeground(new java.awt.Color(255, 255, 255));
        jLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                    .addComponent(jLabelNnTrained, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(152, 152, 152))
            .addGroup(layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(274, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabelNnTrained)
                .addGap(46, 46, 46)
                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//    if ("Start".equals(jButton1.getText())) {
        System.out.println("Training the neural network....");
//         ImageIcon imgThisImg = new ImageIcon("C:/Users/CouriousSoul/Desktop/AutomatedCurrencyExchanger/AutomatedCurrencyExchanger/SystemImages/hourglass.gif");
//         jLabel.setIcon(imgThisImg);
 
        //.setText("Training the neural network....");
//        jProgressBar1.setValue(25);
//         Startsys();
//        System.out.println("jprogressbar value 25");
//        Thread thread = new Thread() {
//         
//        @Override
//        public void run() {
//            
             Startsys();
                 int segmentType = 1;
      SegmentSize();
//       ImageResult ();
//        }
//    };
//    thread.start();
//}  
 
//this.setVisible(false);
//        new CurrencyExchanger().setVisible(true); // Open the CurrencyExchanger UI..
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
        public void Startsys() {

           PatternNeuralNet.trainNet();
        if(PatternNeuralNet.isTrained()){
            System.out.println("setValue(70)");
            //jProgressBar1.setValue(70);
            System.out.println("Testing the neural network....");
            int[] results;
               results = PatternNeuralNet.testNet();
            if(PatternNeuralNet.isTested()){
        System.out.println("Neural network ready....");
          System.out.println("Completed Neural network Testing with  ...");
           System.out.println("Correct classifications of: "+results[0]+" ");
            System.out.println("And Incorrect classifications of: "+results[1]+"");
//            jProgressBar1.setValue(100);
//            jButton2.setVisible(true);
//            jTextPane1.setVisible(true);
                         }
               else{
                  System.out.println("Testing process failed...");
                }
                   }
                    else{
                         System.out.println("Training process failed...");
                    }

}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InitiateSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InitiateSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InitiateSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InitiateSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InitiateSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabelNnTrained;
    // End of variables declaration//GEN-END:variables
}
